# Generated by Django 5.0.7 on 2025-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_carouselslide_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='color',
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_slides/'),
        ),
    ]
