version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "pip list &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-only-key-replace-in-production
      - DJANGO_SETTINGS_MODULE=nordichomes.settings
      - PYTHONPATH=/app
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nordichomes
    ports:
      - "5432:5432"

volumes:
  postgres_data: