lint:
	ruff check --fix

format:
	ruff format

type:
	pyright

activate:
	conda activate djangoenv

run:
	python manage.py runserver

m:
	python manage.py makemigrations 
	python manage.py migrate

user:
	python manage.py createsuperuser
