# Generated by Django 5.0.7 on 2024-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="additional_field_1",
            new_name="f_max",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="additional_field_2",
            new_name="i_max",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="additional_field_3",
            new_name="v_max",
        ),
    ]
