# Generated by Django 5.0.7 on 2024-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_additional_field_1_product_f_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="StockStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="make",
            name="description2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="make",
            name="naslov",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="make",
            name="podnaslov",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="posebnosti",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="st_kanalov",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.discount",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.stockstatus",
            ),
        ),
    ]
