# Generated by Django 5.0.7 on 2024-09-09 13:08

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta


# Function to return a date one month from now
def one_month_from_now():
    return timezone.now() + timedelta(days=30)


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_discount_stockstatus_make_description2_make_naslov_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="Ime_akcije",
            field=models.CharField(
                default="", max_length=255, blank=True, null=True
            ),  # Allow blank and null values
        ),
        migrations.AddField(
            model_name="discount",
            name="velja_do",
            field=models.DateTimeField(
                default=one_month_from_now, blank=True, null=True
            ),  # Default to one month from now
        ),
    ]
