# Generated by Django 5.0.7 on 2024-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_discount_ime_akcije_discount_velja_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="Ime_akcije",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="velja_do",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
