# Generated by Django 5.0.7 on 2024-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_discount_ime_akcije_alter_discount_velja_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockstatus",
            name="in_stock",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
