# Generated by Django 5.0.7 on 2024-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_discount_discount_alter_stockstatus_in_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"ordering": ["velja_do"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="f_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="i_max",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="st_kanalov",
        ),
        migrations.RemoveField(
            model_name="product",
            name="v_max",
        ),
        migrations.AddField(
            model_name="category",
            name="parameter1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="parameter7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
