# Generated by Django 5.0.7 on 2024-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_parameter1_product_parameter2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="parameter1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter4",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter5",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter6",
        ),
        migrations.RemoveField(
            model_name="product",
            name="parameter7",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
