# Generated by Django 5.0.7 on 2024-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0009_remove_product_parameter1_remove_product_parameter2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="parameter1",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter2",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter3",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter4",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter5",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter6",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameter7",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
