# Generated by Django 5.0.7 on 2025-08-19 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_imageasset_area_meta_description_area_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(default='*', max_length=64)),
                ('disallow', models.TextField(blank=True, default='', help_text='One path per line.')),
                ('allow', models.TextField(blank=True, default='', help_text='One path per line.')),
                ('sitemap_url', models.URLField(blank=True, null=True)),
                ('crawl_delay', models.PositiveIntegerField(blank=True, help_text='Seconds.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'user_agent'),
            },
        ),
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="URL path like '/', '/kategorije/osciloskopi/', '/proizvajalci/rigol/'.", max_length=512, unique=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='uploads/og/')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict, help_text="Any extra meta tags, e.g. {'og:type':'website','twitter:card':'summary_large_image'}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('path',),
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='area',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='area',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parameter7',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Ime_akcije',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0–100).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='make',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='make',
            name='description2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='make',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='make',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='make',
            name='naslov',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='make',
            name='podnaslov',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='make',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.area'),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.make'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='posebnosti',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbs/'),
        ),
        migrations.AlterField(
            model_name='stockstatus',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
